apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-argocd-components
  namespace: argocd
  # Add labels to your application object.
  labels:
    name: argocd-components  
spec:
  project: default
  source:
    repoURL: git@github.com:gudiaolabs/argocd-apps
    path: apps/staging/gitops-argocd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true