apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-gudiaolabs
  namespace: argocd
  # Add labels to your application object.
  labels:
    name: argo-config  
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: registry-gudiaolabs
    repoURL: git@github.com:gudiaolabs/argocd-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m0s
      limit: 2
    syncOptions:
    - CreateNamespace=true