apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-argocd-app
  namespace: argocd
  # Add labels to your application object.
  labels:
    name: apps  
spec:
  project: default
  source:
    path: charts/gitops-argocd
    repoURL: 'git@github.com:gudiaolabs/gudiaolabs-charts.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitops-argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true